<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Huruf extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Huruf_model');
        $this->load->library('form_validation');

       
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('huruf/huruf_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Huruf_model->json();
    }

    public function read($id) 
    {
        $row = $this->Huruf_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_huruf' => $row->id_huruf,
		'huruf' => $row->huruf,
		'tanda' => $row->tanda,
	    );
            $this->load->view('huruf/huruf_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('huruf'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('huruf/create_action'),
	    'id_huruf' => set_value('id_huruf'),
	    'huruf' => set_value('huruf'),
	    'tanda' => set_value('tanda'),
	);
        $this->load->view('huruf/huruf_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'huruf' => $this->input->post('huruf',TRUE),
		'tanda' => $this->input->post('tanda',TRUE),
	    );

            $this->Huruf_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('huruf'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Huruf_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('huruf/update_action'),
		'id_huruf' => set_value('id_huruf', $row->id_huruf),
		'huruf' => set_value('huruf', $row->huruf),
		'tanda' => set_value('tanda', $row->tanda),
	    );
            $this->load->view('huruf/huruf_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('huruf'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_huruf', TRUE));
        } else {
            $data = array(
		'huruf' => $this->input->post('huruf',TRUE),
		'tanda' => $this->input->post('tanda',TRUE),
	    );

            $this->Huruf_model->update($this->input->post('id_huruf', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('huruf'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Huruf_model->get_by_id($id);

        if ($row) {
            $this->Huruf_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('huruf'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('huruf'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('huruf', 'huruf', 'trim|required');
	$this->form_validation->set_rules('tanda', 'tanda', 'trim|required');

	$this->form_validation->set_rules('id_huruf', 'id_huruf', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Huruf.php */
/* Location: ./application/controllers/Huruf.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-10 02:12:41 */
/* http://harviacode.com */